# Generated by Django 4.1.7 on 2023-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=100)),
                ("loc", models.CharField(max_length=100)),
            ],
        ),
    ]
