# Generated by Django 4.1.7 on 2023-04-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ename", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("mgr", models.IntegerField()),
                ("hiredate", models.DateField()),
                ("sal", models.IntegerField()),
                ("comm", models.IntegerField(null=True)),
                (
                    "empno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
    ]
