# Generated by Django 4.1.7 on 2023-04-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_emp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emp",
            name="comm",
        ),
        migrations.RemoveField(
            model_name="emp",
            name="id",
        ),
        migrations.AddField(
            model_name="emp",
            name="deptno",
            field=models.ForeignKey(
                default=10, on_delete=django.db.models.deletion.CASCADE, to="app.dept"
            ),
        ),
        migrations.AlterField(
            model_name="emp",
            name="empno",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
